# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NuGetCommand@2
  inputs:
    command: restore
    restoreSolution: 'Shuttle.Access.sln'
    includeNuGetOrg: true
- task: MSBuild@1
  inputs:
   solution: '**/*.csproj'
- task: DotNetCoreCLI@2
  inputs:
    command: publish
    projects: 'Shuttle.Access.Projection/Shuttle.Access.Projection.csproj'
    arguments:  -f netcoreapp2.1 -r linux-x64 -o bin\Release\netcoreapp2.1\publish\ -c Release