# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NuGetCommand@2
  displayName: 'Restore packages'
  inputs:
    command: restore
    restoreSolution: 'Shuttle.Access.sln'
    includeNuGetOrg: true
- task: DotNetCoreCLI@2
  displayName: 'Publish Shuttle.Access.Projection'
  inputs:
    command: publish
    publishWebProjects: false
    projects: 'Shuttle.Access.Projection/Shuttle.Access.Projection.csproj'
    arguments:  '-f netcoreapp3.1 -r linux-x64 -o $(Build.ArtifactStagingDirectory) -c Release'
    modifyOutputPath: true
- task: DotNetCoreCLI@2
  displayName: 'Publish Shuttle.Access.Server'
  inputs:
    command: publish
    publishWebProjects: false
    projects: 'Shuttle.Access.Server/Shuttle.Access.Server.csproj'
    arguments:  '-f netcoreapp3.1 -r linux-x64 -o $(Build.ArtifactStagingDirectory) -c Release'
    modifyOutputPath: true
- task: DotNetCoreCLI@2
  displayName: 'Publish Shuttle.Access.WebApi'
  inputs:
    command: publish
    publishWebProjects: false
    projects: 'Shuttle.Access.WebAPi/Shuttle.Access.WebApi.csproj'
    arguments:  '-f netcoreapp3.1 -r linux-x64 -o $(Build.ArtifactStagingDirectory) -c Release'
    modifyOutputPath: true
