/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AccessContainer: typeof import('./src/components/AccessContainer.vue')['default']
    AccessDataTable: typeof import('./src/components/AccessDataTable.vue')['default']
    AccessDrawer: typeof import('./src/components/AccessDrawer.vue')['default']
    AccessNavbar: typeof import('./src/components/AccessNavbar.vue')['default']
    AccessStrip: typeof import('./src/components/AccessStrip.vue')['default']
    AccessTitle: typeof import('./src/components/AccessTitle.vue')['default']
    BroadsheetStrip: typeof import('./src/components/BroadsheetStrip.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
