<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Shuttle.Contract" Version="21.0.1" />
    <PackageReference Include="Shuttle.Hopper" Version="22.0.1" />
    <PackageReference Include="Shuttle.Recall" Version="22.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Shuttle.Access.Messages\Shuttle.Access.Messages.csproj" />
    <ProjectReference Include="..\Shuttle.Access.SqlServer\Shuttle.Access.SqlServer.csproj" />
    <ProjectReference Include="..\Shuttle.Access\Shuttle.Access.csproj" />
  </ItemGroup>

</Project>
