CREATE TABLE [dbo].[Role] (
    [Id]       UNIQUEIDENTIFIER NOT NULL  CONSTRAINT [DF_Role_Id] DEFAULT newid(),
    [Name] VARCHAR (130)    NOT NULL,
    CONSTRAINT [PK_Role] PRIMARY KEY NONCLUSTERED ([Id] ASC)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_Role]
    ON [dbo].[Role]([Name] ASC);

