trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: Shuttle.Access

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      Copy-Item -Path ".azure/Projection.App.config" -Destination "Shuttle.Access.Projection/App.config" -Force
      Copy-Item -Path ".azure/Projection.log4net.xml" -Destination "Shuttle.Access.Projection/log4net.xml" -Force
      Copy-Item -Path ".azure/Server.App.config" -Destination "Shuttle.Access.Server/App.config" -Force
      Copy-Item -Path ".azure/Server.log4net.xml" -Destination "Shuttle.Access.Server/log4net.xml" -Force
      Copy-Item -Path ".azure/WebApi.App.config" -Destination "Shuttle.Access.WebApi/App.config" -Force
      Copy-Item -Path ".azure/WebApi.log4net.xml" -Destination "Shuttle.Access.WebApi/log4net.xml" -Force
      Copy-Item -Path ".azure/WebApi.web.config" -Destination "Shuttle.Access.WebApi/web.config" -Force
- task: replacetokens@3
  displayName: 'Replace tokens'
  inputs:
    targetFiles: 'Shuttle.Access.WebApi/App.config;Shuttle.Access.WebApi/log4net.xml;Shuttle.Access.Projection/App.config;Shuttle.Access.Projection/log4net.xml;Shuttle.Access.Server/App.config;Shuttle.Access.Server/log4net.xml'
    encoding: 'auto'
    writeBOM: true
    actionOnMissing: 'fail'
    keepToken: false
    tokenPrefix: '#{'
    tokenSuffix: '}#'
    useLegacyPattern: false
    enableTelemetry: false
- task: DotNetCoreCLI@2
  displayName: 'Publish Shuttle.Access.WebApi'
  inputs:
    command: publish
    publishWebProjects: false
    projects: 'Shuttle.Access.WebApi/Shuttle.Access.WebApi.csproj'
    arguments:  '-f netcoreapp3.1 -r win-x64 -o $(Build.BinariesDirectory)/Shuttle.Access.WebAp/ -c Release'
    zipAfterPublish: false
    modifyOutputPath: false
- task: DotNetCoreCLI@2
  displayName: 'Publish Shuttle.Access.Projection'
  inputs:
    command: publish
    publishWebProjects: false
    projects: 'Shuttle.Access.Projection/Shuttle.Access.Projection.csproj'
    arguments:  '-f net50 -r win-x64 -o $(Build.BinariesDirectory)/Shuttle.Access.Projection -c Release'
    zipAfterPublish: false
    modifyOutputPath: false
- task: DotNetCoreCLI@2
  displayName: 'Publish Shuttle.Access.Server'
  inputs:
    command: publish
    publishWebProjects: false
    projects: 'Shuttle.Access.Server/Shuttle.Access.Server.csproj'
    arguments:  '-f net50 -r win-x64 -o $(Build.BinariesDirectory)/Shuttle.Access.Server -c Release'
    zipAfterPublish: false
    modifyOutputPath: false
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.BinariesDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/Shuttle.Access.zip'
    replaceExistingArchive: true    
- task: PublishBuildArtifacts@1
  displayName: 'Publish Build Artifacts'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/Shuttle.Access.zip'
    ArtifactName: 'Shuttle-Access-Services'
    publishLocation: 'Container'