# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: Shuttle.Access

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      Copy-Item -Path ".azure/WebApi.App.config" -Destination "Shuttle.Access.WebApi/App.config" -Force
      Copy-Item -Path ".azure/WebApi.log4net.xml" -Destination "Shuttle.Access.WebApi/log4net.xml" -Force
      Copy-Item -Path ".azure/WebApi.web.config" -Destination "Shuttle.Access.WebApi/web.config" -Force
- task: replacetokens@3
  displayName: 'Replace tokens'
  inputs:
    targetFiles: 'Shuttle.Access.WebApi/App.config;Shuttle.Access.WebApi/log4net.xml;'
    encoding: 'auto'
    writeBOM: true
    actionOnMissing: 'fail'
    keepToken: false
    tokenPrefix: '#{'
    tokenSuffix: '}#'
    useLegacyPattern: false
    enableTelemetry: false
- task: DotNetCoreCLI@2
  displayName: 'Publish Shuttle.Access.WebApi'
  inputs:
    command: publish
    publishWebProjects: false
    projects: 'Shuttle.Access.WebApi/Shuttle.Access.WebApi.csproj'
    arguments:  '-f netcoreapp3.1 -r win-x64 -o $(Build.BinariesDirectory)/webapi/ -c Release'
    zipAfterPublish: false
    modifyOutputPath: false
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.BinariesDirectory)/webapi'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/Shuttle.Access.WebApi.zip'
    replaceExistingArchive: true    
- task: PublishBuildArtifacts@1
  displayName: 'Publish Build Artifacts'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/Shuttle.Access.WebApi.zip'
    ArtifactName: 'Shuttle-Access-WebApi'
    publishLocation: 'Container'