// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shuttle.Access.SqlServer;

#nullable disable

namespace Shuttle.Access.Data.Migrations
{
    [DbContext(typeof(AccessDbContext))]
    [Migration("20260117154311_Tenant_Migration")]
    partial class Tenant_Migration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Shuttle.Access.SqlServer.Models.Identity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("DateActivated")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("DateRegistered")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("GeneratedPassword")
                        .HasMaxLength(65)
                        .HasColumnType("nvarchar(65)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("RegisteredBy")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Name" }, "UX_Identity_Name")
                        .IsUnique();

                    b.ToTable("Identity", "access");
                });

            modelBuilder.Entity("Shuttle.Access.SqlServer.Models.IdentityRole", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdentityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TenantId", "IdentityId", "RoleId");

                    b.HasIndex("IdentityId");

                    b.HasIndex("TenantId", "RoleId");

                    b.ToTable("IdentityRole", "access");
                });

            modelBuilder.Entity("Shuttle.Access.SqlServer.Models.IdentityTenant", b =>
                {
                    b.Property<Guid>("IdentityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("IdentityId", "TenantId");

                    b.HasIndex("TenantId");

                    b.ToTable("IdentityTenant", "access");
                });

            modelBuilder.Entity("Shuttle.Access.SqlServer.Models.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Name" }, "UX_Permission_Name")
                        .IsUnique();

                    b.ToTable("Permission", "access");
                });

            modelBuilder.Entity("Shuttle.Access.SqlServer.Models.PermissionTenant", b =>
                {
                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PermissionId", "TenantId");

                    b.HasIndex("TenantId");

                    b.ToTable("PermissionTenant", "access");
                });

            modelBuilder.Entity("Shuttle.Access.SqlServer.Models.Role", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("TenantId", "Id");

                    b.HasIndex(new[] { "Name" }, "UX_Role_Name")
                        .IsUnique();

                    b.ToTable("Role", "access");
                });

            modelBuilder.Entity("Shuttle.Access.SqlServer.Models.RolePermission", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TenantId", "RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermission", "access");
                });

            modelBuilder.Entity("Shuttle.Access.SqlServer.Models.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTimeOffset>("DateRegistered")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ExpiryDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("IdentityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IdentityName")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Token")
                        .IsRequired()
                        .HasColumnType("varbinary(900)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex(new[] { "IdentityId" }, "UX_Session_IdentityId")
                        .IsUnique();

                    b.HasIndex(new[] { "IdentityName" }, "UX_Session_IdentityName")
                        .IsUnique();

                    b.HasIndex(new[] { "Token" }, "UX_Session_Token")
                        .IsUnique();

                    b.ToTable("Session", "access");
                });

            modelBuilder.Entity("Shuttle.Access.SqlServer.Models.SessionPermission", b =>
                {
                    b.Property<Guid>("SessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SessionId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("SessionPermission", "access");
                });

            modelBuilder.Entity("Shuttle.Access.SqlServer.Models.SessionTokenExchange", b =>
                {
                    b.Property<Guid>("ExchangeToken")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("ExpiryDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("SessionToken")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ExchangeToken");

                    b.ToTable("SessionTokenExchange", "access");
                });

            modelBuilder.Entity("Shuttle.Access.SqlServer.Models.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LogoSvg")
                        .IsRequired()
                        .HasMaxLength(2147483647)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogoUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Name" }, "UX_Tenant_Name")
                        .IsUnique();

                    b.ToTable("Tenant", "access");
                });

            modelBuilder.Entity("Shuttle.Access.SqlServer.Models.IdentityRole", b =>
                {
                    b.HasOne("Shuttle.Access.SqlServer.Models.Identity", "Identity")
                        .WithMany("IdentityRoles")
                        .HasForeignKey("IdentityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shuttle.Access.SqlServer.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("TenantId", "RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Identity");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Shuttle.Access.SqlServer.Models.IdentityTenant", b =>
                {
                    b.HasOne("Shuttle.Access.SqlServer.Models.Identity", "Identity")
                        .WithMany("IdentityTenants")
                        .HasForeignKey("IdentityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shuttle.Access.SqlServer.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Identity");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Shuttle.Access.SqlServer.Models.PermissionTenant", b =>
                {
                    b.HasOne("Shuttle.Access.SqlServer.Models.Permission", "Permission")
                        .WithMany("PermissionTenants")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shuttle.Access.SqlServer.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Shuttle.Access.SqlServer.Models.RolePermission", b =>
                {
                    b.HasOne("Shuttle.Access.SqlServer.Models.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shuttle.Access.SqlServer.Models.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("TenantId", "RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Shuttle.Access.SqlServer.Models.Session", b =>
                {
                    b.HasOne("Shuttle.Access.SqlServer.Models.Identity", "Identity")
                        .WithMany()
                        .HasForeignKey("IdentityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shuttle.Access.SqlServer.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId");

                    b.Navigation("Identity");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Shuttle.Access.SqlServer.Models.SessionPermission", b =>
                {
                    b.HasOne("Shuttle.Access.SqlServer.Models.Permission", "Permission")
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shuttle.Access.SqlServer.Models.Session", "Session")
                        .WithMany("SessionPermissions")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Shuttle.Access.SqlServer.Models.Identity", b =>
                {
                    b.Navigation("IdentityRoles");

                    b.Navigation("IdentityTenants");
                });

            modelBuilder.Entity("Shuttle.Access.SqlServer.Models.Permission", b =>
                {
                    b.Navigation("PermissionTenants");

                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("Shuttle.Access.SqlServer.Models.Role", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("Shuttle.Access.SqlServer.Models.Session", b =>
                {
                    b.Navigation("SessionPermissions");
                });
#pragma warning restore 612, 618
        }
    }
}
