//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shuttle.Access.Application {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shuttle.Access.Application.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;Access Administrator&apos; role does not have the required &apos;access://*&apos; permission..
        /// </summary>
        public static string AdministratorPermissionException {
            get {
                return ResourceManager.GetString("AdministratorPermissionException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timed out waiting for the administrator role to be registered..
        /// </summary>
        public static string AdministratorRoleException {
            get {
                return ResourceManager.GetString("AdministratorRoleException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not register/find all required permissions.  Please restart the server to try again..
        /// </summary>
        public static string PermissionsException {
            get {
                return ResourceManager.GetString("PermissionsException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password has not been set.  Please call `UsePassword` first..
        /// </summary>
        public static string RegisterSessionPasswordNotSetException {
            get {
                return ResourceManager.GetString("RegisterSessionPasswordNotSetException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The token has not been set.  Please call `UseToken` or `UseDelegation` first..
        /// </summary>
        public static string RegisterSessionTokenNotSetException {
            get {
                return ResourceManager.GetString("RegisterSessionTokenNotSetException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration type already set to &apos;{0}&apos;..
        /// </summary>
        public static string SessionRegistrationTypeException {
            get {
                return ResourceManager.GetString("SessionRegistrationTypeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No registration type has been set..
        /// </summary>
        public static string SessionRegistrationTypeNoneException {
            get {
                return ResourceManager.GetString("SessionRegistrationTypeNoneException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timed out waiting for the system tenant to be registered..
        /// </summary>
        public static string SystemTenantException {
            get {
                return ResourceManager.GetString("SystemTenantException", resourceCulture);
            }
        }
    }
}
