<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Shuttle.Contract" Version="21.0.1" />
    <PackageReference Include="Shuttle.Mediator" Version="21.0.2" />
    <PackageReference Include="Shuttle.Hopper" Version="22.0.1" />
    <PackageReference Include="Shuttle.Recall" Version="22.0.1" />
    <PackageReference Include="Shuttle.Recall.SqlServer.EventProcessing" Version="22.0.1" />
    <PackageReference Include="Shuttle.Recall.SqlServer.Storage" Version="22.0.1" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Resources.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Shuttle.Access.WebApi.Contracts\Shuttle.Access.WebApi.Contracts.csproj" />
    <ProjectReference Include="..\Shuttle.Access\Shuttle.Access.csproj" />
  </ItemGroup>

</Project>
