//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shuttle.Access.AspNetCore {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shuttle.Access.AspNetCore.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find a session for the current context..
        /// </summary>
        public static string ContextSessionNotFound {
            get {
                return ResourceManager.GetString("ContextSessionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISessionContext implementation expected to be type SessionContext..
        /// </summary>
        public static string SessionContextException {
            get {
                return ResourceManager.GetString("SessionContextException", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid GUID received for header &apos;Shuttle-Access-Tenant-Id&apos;..
        /// </summary>
        public static string InvalidTenantIdHeaderException {
            get {
                return ResourceManager.GetString("InvalidTenantIdHeaderException", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Option &apos;{0}&apos; may not be empty..
        /// </summary>
        public static string OptionMissingException {
            get {
                return ResourceManager.GetString("OptionMissingException", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Option &apos;{0}&apos; is not a valid URI..
        /// </summary>
        public static string OptionUriException {
            get {
                return ResourceManager.GetString("OptionUriException", resourceCulture);
            }
        }
    }
}
