//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shuttle.Access {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shuttle.Access.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;Administrator&apos; role could not be found..
        /// </summary>
        public static string AdministratorRoleMissingException {
            get {
                return ResourceManager.GetString("AdministratorRoleMissingException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find a configuration section with name &quot;accessClient&quot; or &quot;shuttle/accessClient&quot;..
        /// </summary>
        public static string ClientSectionException {
            get {
                return ResourceManager.GetString("ClientSectionException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find a connection string with name &apos;{0}&apos;..
        /// </summary>
        public static string ConnectionStringMissing {
            get {
                return ResourceManager.GetString("ConnectionStringMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not delete the session..
        /// </summary>
        public static string DeleteSessionException {
            get {
                return ResourceManager.GetString("DeleteSessionException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity &apos;{0}&apos; is already in role with id &apos;{1}&apos;..
        /// </summary>
        public static string DuplicateIdentityRoleException {
            get {
                return ResourceManager.GetString("DuplicateIdentityRoleException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission with Id &apos;{0}&apos; already exists on role &apos;{1}&apos;..
        /// </summary>
        public static string DuplicateRolePermissionException {
            get {
                return ResourceManager.GetString("DuplicateRolePermissionException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not determine the identity from the HttpContext..
        /// </summary>
        public static string HttpContextIdentityNotFound {
            get {
                return ResourceManager.GetString("HttpContextIdentityNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity with name &apos;{0}&apos; is inactive..
        /// </summary>
        public static string IdentityInactiveException {
            get {
                return ResourceManager.GetString("IdentityInactiveException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The JWT token provided does not contain a claim type representing the identity name..
        /// </summary>
        public static string IdentityNameClaimNotFound {
            get {
                return ResourceManager.GetString("IdentityNameClaimNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;Authorization&apos; header contains a valid scheme but either has an invalid token, or there is no issuer configuration matching that of the token..
        /// </summary>
        public static string InvalidAuthenticationHeader {
            get {
                return ResourceManager.GetString("InvalidAuthenticationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid credentials..
        /// </summary>
        public static string InvalidCredentialsException {
            get {
                return ResourceManager.GetString("InvalidCredentialsException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password authentication is not allowed.  Please use a token..
        /// </summary>
        public static string PasswordAuthenticationNotAllowed {
            get {
                return ResourceManager.GetString("PasswordAuthenticationNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;PasswordHash&apos; may not be empty..
        /// </summary>
        public static string PasswordHashException {
            get {
                return ResourceManager.GetString("PasswordHashException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission with Id &apos;{0}&apos; does not exist on role &apos;{1}&apos;..
        /// </summary>
        public static string PermissionNotFoundException {
            get {
                return ResourceManager.GetString("PermissionNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &apos;{0}&apos; has not changed.  Cannot apply value of &apos;{1}&apos;..
        /// </summary>
        public static string PropertyUnchangedException {
            get {
                return ResourceManager.GetString("PropertyUnchangedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is already a password reset token registered..
        /// </summary>
        public static string RegisterPasswordResetTokenException {
            get {
                return ResourceManager.GetString("RegisterPasswordResetTokenException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not register the session..
        /// </summary>
        public static string RegisterSessionException {
            get {
                return ResourceManager.GetString("RegisterSessionException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required option &apos;{0}&apos; is missing..
        /// </summary>
        public static string RequiredOptionMissing {
            get {
                return ResourceManager.GetString("RequiredOptionMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role &apos;{0}&apos; does not exist on user &apos;{1}&apos;..
        /// </summary>
        public static string RoleNotFoundException {
            get {
                return ResourceManager.GetString("RoleNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to `IdentityName` may not be empty..
        /// </summary>
        public static string SessionIdentityNameRequired {
            get {
                return ResourceManager.GetString("SessionIdentityNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find a valid session..
        /// </summary>
        public static string SessionNotFound {
            get {
                return ResourceManager.GetString("SessionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No token could be retrieved to fulfill the request..
        /// </summary>
        public static string SessionTokenException {
            get {
                return ResourceManager.GetString("SessionTokenException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The session token has expired.  Please log in again..
        /// </summary>
        public static string SessionTokenExpiredException {
            get {
                return ResourceManager.GetString("SessionTokenExpiredException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find an identity with name &apos;{0}&apos;..
        /// </summary>
        public static string UnknownIdentityException {
            get {
                return ResourceManager.GetString("UnknownIdentityException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; is already set to &apos;{1}&apos;..
        /// </summary>
        public static string ValueAlreadySetException {
            get {
                return ResourceManager.GetString("ValueAlreadySetException", resourceCulture);
            }
        }
    }
}
