exec RegisterPermission 'access://role/register'
exec RegisterPermission 'access://role/remove'
exec RegisterPermission 'access://role/view'
exec RegisterPermission 'access://identity/register'
exec RegisterPermission 'access://identity/remove'
exec RegisterPermission 'access://identity/view'
exec RegisterPermission 'access://permission/register'
exec RegisterPermission 'access://permission/remove'
exec RegisterPermission 'access://dashboard/view'

exec RegisterRole 'Anonymous'
exec RegisterRolePermission 'Anonymous', 'access://dashboard/view'