exec RegisterAvailablePermission 'access://roles/register'
exec RegisterAvailablePermission 'access://roles/remove'
exec RegisterAvailablePermission 'access://roles/view'
exec RegisterAvailablePermission 'access://users/register'
exec RegisterAvailablePermission 'access://users/remove'
exec RegisterAvailablePermission 'access://users/view'
exec RegisterAvailablePermission 'access://permissions/register'
exec RegisterAvailablePermission 'access://permissions/remove'
exec RegisterAvailablePermission 'access://dashboard/view'

exec RegisterRole 'Anonymous'
exec RegisterRolePermission 'Anonymous', 'access://dashboard/view'