version: "3.9"
services:
    azurite:
        image: mcr.microsoft.com/azure-storage/azurite
        hostname: azurite
    database:
        image: shuttle/access-sqlserver-linux:latest
        hostname: database
    server:
        image:
            shuttle/access-server:latest
        environment:
            - CONFIGURATION_FOLDER=.
        depends_on:
            - "azurite"
            - "database"
        volumes:
            - type: bind
              source: ./server-appsettings.json
              target: /opt/shuttle.access.server/appsettings.json
            - type: bind
              source: ./logs/Shuttle.Access.Server
              target: /opt/shuttle.access.server/logs
    projection:
        image:
            shuttle/access-projection:latest
        environment:
            - CONFIGURATION_FOLDER=.
        depends_on:
            - "database"
        volumes:
            - type: bind
              source: ./projection-appsettings.json
              target: /opt/shuttle.access.projection/appsettings.json
            - type: bind
              source: ./logs/Shuttle.Access.Projection
              target: /opt/shuttle.access.projection/logs
    web-api:
        image:
            shuttle/access-webapi:latest
        environment:
            - ASPNETCORE_URLS=http://*:5599
            - CONFIGURATION_FOLDER=.
        depends_on:
            - "azurite"
            - "server"
        ports:
            - "5599:5599"
        volumes:
            - type: bind
              source: ./webapi-appsettings.json
              target: /opt/shuttle.access.webapi/appsettings.json
            - type: bind
              source: ./logs/Shuttle.Access.WebApi
              target: /opt/shuttle.access.webapi/logs
    front-end:
        image:
            shuttle/access-vue:latest
        ports:
            - "8080:80"