FROM mcr.microsoft.com/dotnet/runtime:6.0

COPY ./deployment/Shuttle.Access.Server/. /opt/shuttle.access.server/.

WORKDIR /opt/shuttle.access.server/

ENTRYPOINT ["/opt/shuttle.access.server/Shuttle.Access.Server" ]
