version: "3.9"
services:
    azurite:
        image: mcr.microsoft.com/azure-storage/azurite
        hostname: azurite
    database:
        image: shuttle/access-sqlserver-linux:latest
        hostname: database
    server:
        image:
            shuttle/access-server:latest
        depends_on:
            - "azurite"
            - "database"
    projection:
        image:
            shuttle/access-projection:latest
        depends_on:
            - "database"
    web-api:
        image:
            shuttle/access-webapi:latest
        environment:
            - ASPNETCORE_URLS=http://*:5599
        depends_on:
            - "azurite"
            - "server"
        ports:
            - "5599:5599"
    front-end:
        image:
            shuttle/access-vue:latest
        ports:
            - "8080:80"