version: "3.9"
services:
    jeager:
        image: jaegertracing/all-in-one:1.6
        environment:
            - COLLECTOR_ZIPKIN_HTTP_PORT=9411
        ports:
            - "5775:5775/udp"
            - "6831:6831/udp"
            - "6832:6832/udp"
            - "5778:5778"
            - "16686:16686"
            - "14268:14268"
            - "9411:9411"
    azurite:
        image: mcr.microsoft.com/azure-storage/azurite
        hostname: azurite
    database:
        image: shuttle/access-sqlserver-linux:latest
        hostname: database
    server:
        image:
            shuttle/access-server:latest
        depends_on:
            - "azurite"
            - "database"
            - "jeager"
    projection:
        image:
            shuttle/access-projection:latest
        depends_on:
            - "database"
            - "jeager"
    web-api:
        image:
            shuttle/access-webapi:latest
        environment:
            - ASPNETCORE_URLS=http://*:5599
        depends_on:
            - "azurite"
            - "server"
            - "jeager"
        ports:
            - "5599:5599"
    front-end:
        image:
            shuttle/access-vue:latest
        ports:
            - "8080:80"