version: "3.9"
services:
    azurite:
        image: mcr.microsoft.com/azure-storage/azurite
        hostname: azurite
    database:
        image: shuttle/access-sqlserver-linux:latest
        hostname: database
        ports:
            - "2433:1433"
    server:
        image:
            shuttle/access-server:latest
        environment:
            - CONFIGURATION_FOLDER=.
        depends_on:
            - "azurite"
            - "database"
        volumes:
            - type: bind
              source: ./server-appsettings.json
              target: /opt/shuttle.access.server/appsettings.json
    web-api:
        image:
            shuttle/access-webapi:latest
        environment:
            - ASPNETCORE_URLS=http://*:5599
            - CONFIGURATION_FOLDER=.
        depends_on:
            - "azurite"
            - "server"
        ports:
            - "5599:5599"
        volumes:
            - type: bind
              source: ./webapi-appsettings.json
              target: /opt/shuttle.access.webapi/appsettings.json
    front-end:
        image:
            shuttle/access-vue:latest
        environment:
           - VITE_API_URL=http://localhost:5599
           - VITE_API_ALLOW_PASSWORD_AUTHENTICATION=true
        ports:
            - "3000:80"