version: "3.9"
services:
    azurite:
        image: mcr.microsoft.com/azure-storage/azurite
        hostname: azurite
    database:
        image: shuttle/access/linux-sqlserver-demo
        hostname: database
    server:
        image:
            shuttle/access/server
        depends_on:
            - "azurite"
            - "database"
        build:
            context: .
            dockerfile: dockerfile-server
    projection:
        image:
            shuttle/access/projection
        build:
            context: .
            dockerfile: dockerfile-projection
        depends_on:
            - "database"
    web-api:
        image:
            shuttle/access/webapi
        environment:
            - ASPNETCORE_URLS=http://*:5599
        depends_on:
            - "azurite"
            - "server"
        build:
            context: .
            dockerfile: dockerfile-webapi   
        ports:
            - "5599:5599"
    front-end:
        image:
            shuttle/access/vue
        ports:
            - "8080:80"