FROM mcr.microsoft.com/dotnet/aspnet:10.0

COPY ./deployment/Shuttle.Access.WebApi/. /opt/shuttle.access.webapi/.

WORKDIR /opt/shuttle.access.webapi/

ENTRYPOINT ["dotnet", "Shuttle.Access.WebApi.dll"]