drop table [access].[SessionTokenExchange]
drop table [access].[SessionPermission]
drop table [access].[Session]
drop table [access].[RolePermission]
drop table [access].[Role]
drop table [access].[Identity]
drop table [access].[IdentityRole]
drop table [access].[Permission]