delete from [dbo].[AvailablePermission]
delete from [dbo].[EventStore]
delete from [dbo].[EventType]
delete from [dbo].[KeyStore]
delete from [dbo].[SnapshotStore]

delete from [dbo].[Projection]
delete from [dbo].[Session]
delete from [dbo].[SessionPermission]
delete from [dbo].[SystemRole]
delete from [dbo].[SystemRolePermission]
delete from [dbo].[SystemUser]
delete from [dbo].[SystemUserRole]