<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>0f53a9ee-2e97-449e-814b-d645a3a1d138</UserSecretsId>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.11">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.11">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="10.0.11" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="10.0.11" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="10.0.11" />
    <PackageReference Include="Shuttle.Recall" Version="22.0.1" />
    <PackageReference Include="Shuttle.Recall.SqlServer.EventProcessing" Version="22.0.1" />
    <PackageReference Include="Shuttle.Recall.SqlServer.Storage" Version="22.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Shuttle.Access\Shuttle.Access.csproj" />
  </ItemGroup>

</Project>
